# -*- coding: utf-8 -*-
"""P1_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FRpCfP8kB_bAhHKCxj8g0IXQQVX48OB
"""

#board
position1 = input().split()
position2 = input().split()
x1,y1 = int(position1[0]),int(position1[1])
x2,y2 = int(position2[0]),int(position2[1])

if (x1==x2 and y1==y2) or checkerboard[x2][y2]==1:
  print("No")
elif x2 - x1 == 1 and y1==y2:
  print("Yes")
else:
  print("No")